### ISSUE TITLE
Make sure Codacy is respecting the configuration file

### ISSUE THREAD

**Issue by abelsiqueira** [nlesc-recruit/cudawrappers#104]
Make sure Codacy is respecting the configuration file created in #98

**Comment by abelsiqueira** [comment]
I made a simple test with PR #131 
- I included duplication checks and duplicated code and it was picked up (https://app.codacy.com/gh/nlesc-recruit/cudawrappers/commit?bid=28025423&cid=626184480)
- I enforced no duplication check and no information about duplication appears (https://app.codacy.com/gh/nlesc-recruit/cudawrappers/commit?bid=28025423&cid=626185333)

Apparently, it is picking up the information from the Codacy configuration file.

**Comment by loostrum** [comment]
Seems like this is working as intended
