### ISSUE TITLE
Host API documentation on readthedocs

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#121]

**Comment by jspaaks** [comment]
Also add a link to the documentation (https://readthedocs.org/projects/cudawrappers) from the README.

Maybe as a badge: [![Documentation Status](https://readthedocs.org/projects/cudawrappers/badge/?version=latest)](https://cudawrappers.readthedocs.io/en/latest/?badge=latest)

```markdown
[![Documentation Status](https://readthedocs.org/projects/cudawrappers/badge/?version=latest)](https://cudawrappers.readthedocs.io/en/latest/?badge=latest)
```

**Comment by fdiblen** [comment]
done in #135
