### ISSUE TITLE
Consider renaming usage repositories

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/cudawrappers#127]
From PR #111

@bouweandela suggested

> It might be good to include cudawrappers in the name of the example repo. As the number of repos in the organization grows, it may not be clear anymore that this example is about using cudawrappers. This context is also lost when someone forks the example repo.

**Comment by jspaaks** [comment]
Not sure about that one. I think I'd prefer to rename to organization to `cudawrappers` instead, and only have it contain cudawrappery things.

**Comment by loostrum** [comment]
This org is not just cudawrappers though, it also contains PowerSensor, so I would agree with Bouwe to add cudawrappers to the names.

**Comment by csbnw** [comment]
The repositories have been renamed (the `cudawrappers-` prefix is added). The new URLs are:
- https://github.com/nlesc-recruit/cudawrappers-usage-example-git-submodules
- https://github.com/nlesc-recruit/cudawrappers-usage-example-cmake-pull
- https://github.com/nlesc-recruit/cudawrappers-usage-example-locally-installed
It is a bit silly that the latter two are merely placeholders, but that is beyond the scope of this issue.
