### ISSUE TITLE
Make an RSD entry

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#13]
Blocked by:
- #8 
- #12

**Comment by jspaaks** [comment]
Once we have an entry in the Research Software Directory, we can add a badge like [![Research Software Directory](https://img.shields.io/badge/rsd-cudawrappers-00a3e3.svg)](https://www.research-software.nl/software/cudawrappers)

using:

```markdown
[![Research Software Directory](https://img.shields.io/badge/rsd-cudawrappers-00a3e3.svg)](https://www.research-software.nl/software/cudawrappers)
```
