### ISSUE TITLE
Codacy workflow is failing

### ISSUE THREAD

**Issue by abelsiqueira** [nlesc-recruit/cudawrappers#130]
Codacy is apparently having some issues submitting the clang-tidy results. See for instance https://github.com/nlesc-recruit/cudawrappers/runs/5396144469?check_suite_focus=true#step:4:316.
Notice that this is not related to whether the clang-tidy checks are working or not, but whether the workflow is sending this information to Codacy.

**Comment by abelsiqueira** [comment]
I have assigned myself to both Codacy issues, because they might be related

**Comment by fdiblen** [comment]
done in #136

**Comment by abelsiqueira** [comment]
Merged
