### ISSUE TITLE
Links in the online documentation do not work

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#133]
README.md has links to README.dev.md and CONTRIBUTING.md. When hosting the documenatiton on readthedocs, these links do not work.

**Comment by csbnw** [comment]
See https://github.com/nlesc-recruit/cudawrappers/pull/203.
Unfortunately, the problem still persists.

**Comment by csbnw** [comment]
We looked into this again, but still can't seem to fix it, as the examples shown in the documentation simply don't work. Therefore, we will postpone fixing this issue for some future release (not 0.5.0).

**Comment by laurasootes** [comment]
@csbnw 

It seems to work when using the full weblinks to the files (see [branch](https://github.com/nlesc-recruit/cudawrappers/tree/readthedocs_links)). I recreated the readthedocs page from a fork, and there the links do work:
[fork rtd](https://cudawrapperss.readthedocs.io/en/latest/#)

Or is it undesirable to do it this way?

**Comment by csbnw** [comment]
Using the full weblinks was indeed one of the things that was considered before. It is not a very elegant solution, arguably better than having links that do not function at all.
