### ISSUE TITLE
Decide if we want to have pre-commit hooks

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#15]
Decide if we want to have pre-commit hooks. If the answer yes, add a hook.
See: https://github.com/pocc/pre-commit-hooks

**Comment by jspaaks** [comment]
If think we can just add this, because people who don't want them don't have to use them.

**Comment by abelsiqueira** [comment]
I agree.

**Comment by fdiblen** [comment]
We should make it optional.

**Comment by bouweandela** [comment]
Relevant for the configuration: @csbnw mentioned that at Astron they make use of:
- C++ code: `clang-format` and `clang-tidy` with [Google code style](https://google.github.io/styleguide/cppguide.html) 
- Cmake files: [`cmake-format` and `cmake-lint`](https://cmake-format.readthedocs.io/en/latest/)

**Comment by bouweandela** [comment]
It might be nice to make use of the [pre-commit](https://pre-commit.com/hooks.html) framework, anyone an opinion on this?

**Comment by csbnw** [comment]
One of the development teams at ASTRON that works on software for LOFAR and the SKA is called "Team Schaap". They have a [repository](https://git.astron.nl/RD/schaapcommon) with commonly used files, including [`clang-format`](https://git.astron.nl/RD/schaapcommon/-/blob/master/.clang-format) and [`clang-tidy`](https://git.astron.nl/RD/schaapcommon/-/blob/master/.clang-tidy). The formatting is applied by calling [this](https://git.astron.nl/RD/schaapcommon/-/blob/master/scripts/run-format.sh) script. The `.clang-tidy` is recognized by an IDE (e.g. Visual Studio Code) when an extension like [Clang-Tidy](https://marketplace.visualstudio.com/items?itemName=notskm.clang-tidy) is used. While `clang-format` is typically strictly enforced in the CI, `clang-tidy` is used more loosely and mostly prevents comments on MR's that could (easily) have been avoided by fixing the suggestions.

**Comment by jspaaks** [comment]
We have to mindful though that using files from for example https://git.astron.nl/RD/schaapcommon affects the license that this repo can legally have
