### ISSUE TITLE
Rename example repositories

### ISSUE THREAD

**Issue by loostrum** [nlesc-recruit/cudawrappers#174]
The names of the three example repositories do not refer to cudawrappers in any way. As the nlesc-recruit github org contains more than just cudawrappers, I suggest renaming them to cudawrappers-usage-example-xxx
The three repos:
https://github.com/nlesc-recruit/usage-example-git-submodules
https://github.com/nlesc-recruit/usage-example-locally-installed
https://github.com/nlesc-recruit/usage-example-cmake-pull

**Comment by bouweandela** [comment]
Duplicate of #127
