### ISSUE TITLE
Fix Device()

### ISSUE THREAD

**Issue by laurasootes** [nlesc-recruit/cudawrappers#187]
https://github.com/nlesc-recruit/cudawrappers/blob/db1f3ff9e6e9dbffe51cb0d648f3e0a4c0023280/include/cudawrappers/cu.hpp#L190C1-L190C48

Fix Device in  cu.hpp -> Device getDevice()

**Comment by matmanc** [comment]
Fixed in https://github.com/nlesc-recruit/cudawrappers/pull/204.
