### ISSUE TITLE
Set up CI for at least the same linters as precommit hooks

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/cudawrappers#26]

**Comment by abelsiqueira** [comment]
I assigned myself to evaluate the alternative pre-commit.ci, as we discussed yesterday.

**Comment by abelsiqueira** [comment]
pre-commit.ci had issues finding the executables. They have no separate issue tracker and I could not find useful information on a quick search around pre-commit's repo.
Furthermore, pre-commit.ci needs write permission to a lot of things.

Therefore, I am closing the PR and removing pre-commit.ci for now.

**Comment by fdiblen** [comment]
We won't be using pre-commit.ci service. Instead we will try to do the linting in a workflow.

**Comment by jspaaks** [comment]
PR #115 adds linting in ci using the project's default precommit hooks

**Comment by fdiblen** [comment]
done in #115
