### ISSUE TITLE
Include cuda_runtime in cu.hpp

### ISSUE THREAD

**Issue by loostrum** [nlesc-recruit/cudawrappers#296]
After merging the HIP branch, the main branch now no longer includes `cuda_runtime.h` in `cu.hpp`, see [here](https://github.com/nlesc-recruit/cudawrappers/blob/5098d73a8538d888351e3f08d0f7e11db57b77d6/include/cudawrappers/cu.hpp#L16-L19)
For HIP, the hip runtime _is_ included. Should we include `cuda_runtime.h` (or perhaps `cuda_runtime_api.h`) in `cu.hpp`?
Existing code in e.g. `ccglib` is now broken with CUDA because `dim3` no longer exists when only including cudawrappers.

**Comment by csbnw** [comment]
Since `cuda_runtime_api.h` was there before, I indeed agree that it should be restored.

**Comment by loostrum** [comment]
Fixed in #297
