### ISSUE TITLE
Write developer documentation on running linters locally

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/cudawrappers#32]

**Comment by fdiblen** [comment]
one option is https://github.com/danmar/cppcheck

**Comment by abelsiqueira** [comment]
- [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html)
- Maybe more from https://github.com/fffaraz/awesome-cpp#static-code-analysis

**Comment by abelsiqueira** [comment]
Following #23, here's a short summary so I don't work on this issue at the same time:

Install
- `cmake-format` (https://cmake-format.readthedocs.io/en/latest/installation.html)
- VSCode extension for `cmake-format` (https://marketplace.visualstudio.com/items?itemName=cheshirekow.cmake-format)
- `clang-tidy` (https://clang.llvm.org/extra/clang-tidy/)
- VSCode extension `clang-tidy` (https://marketplace.visualstudio.com/items?itemName=notskm.clang-tidy)
- `clang-format` (https://clang.llvm.org/docs/ClangFormat.html)
- VSCode extension Clang-Format (https://marketplace.visualstudio.com/items?itemName=xaver.clang-format)

**Comment by abelsiqueira** [comment]
#59 has the commands.

**Comment by abelsiqueira** [comment]
PR was merged.
