### ISSUE TITLE
Add list of software and hardware requirements to the documentation

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/cudawrappers#34]

**Comment by john-romein** [comment]
Ideally, the only software requirement is CUDA 10 or higher (on any platform), and the only hardware requirement is an NVIDIA GPU (Pascal or newer).

**Comment by fdiblen** [comment]
- At least test on DAS6, optionally DAS5
- Would be nice if you have another (Linux) system available for testing
- At least support Linux, testing on Windows and macOS would be nice to have
- Support CUDA 10 and up, support GPU architecture Pascal and up
- We can easily support loading of different CUDA version on DAS6 for CI testing. It would be good to test multiple different versions of CUDA in the CI test.

_Originally posted by @svlugt in https://github.com/nlesc-recruit/cudawrappers/issues/6#issuecomment-1055461364_

**Comment by fdiblen** [comment]
fixed by #102
