### ISSUE TITLE
List of ideas

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#5]
## General
~~1. Find a better name for the repo~~ #8 
~~1. Capitalization of the repo name? Should be consistent with name of the library IMO~~ #8 
~~1. fix copyright issue in README.md~~ #11 
~~1. Write something about the added value of the wrapper. What thing is now easier?~~ #12
~~1. Describe what this code does and why a user needs it~~ #12
~~1. Is there value to having a sibling repo (say, cuda-wrappers-it) with a release of cuda-wrappers as a submodule?~~ #9 
~~1. Make an RSD entry~~ #13 
~~1. add editorconfig~~ #14
~~1. pre-commit hooks for clang clang-tidy https://github.com/pocc/pre-commit-hooks~~ #15
~~1. Add a Citation file~~ #17 
~~1. Add contributing guide (CONTRIBUTING.md)~~ #18 
~~1. add a PR template, an issue template~~ #19
~~1. Add Code of conduct~~ #20
~~1. Add badges: fair-software, repo badge, license badge, rsd badge, CI badges, zenodo badge, checklist badge~~ #21

## Code improvements
~~1. organize the files and think about folder structure~~ #9 
~~1. Clean up the code: delete commented out code~~ #24 

## CI
~~1. look for options to do static analysis and add a GH action~~ #23 
~~1. Add integration test programs~~ See #9 
~~1. CI with self-hosted runners to run the integration tests~~ #25
~~1. continuous integration for at least the same linters as precommit hooks~~ #26
~~1. add cffconvert-github-action~~ #27

1. check if PRs will be a problem for self-hosted runners

## Documentation
~~1. look for alternatives for code documentation and build the documentation with CI~~ #28
~~1. document how to build the documentation locally~~ #29
~~1. notes on how to make a release~~ #30
~~1. notes on precommit hooks~~ #31
~~1. notes on running the linters locally~~ #32
~~1. notes on how to build the library libcu.so~~ #33
~~1. add list of software and hardware requirements~~ #34
~~1. add list of supported CUDA versions and operating systems~~ #34
~~1. add a section about 'alternatives' doing the same or similar thing~~ #35
~~1. improve code documentation --> document functions~~ #36
1. think about remote development/debugging using VSCode's remote containers extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
1. Consider creating a conan package https://conan.io
1. Any IDE extensions or configuration needed?

## Build system
~~1. Is libcu.so a good name?~~ #8 
~~1. Can we steal some ideas from https://github.com/nlesc-dirac/sagecal/blob/master/CMakeLists.txt ?~~ #9 

## API
1.~~The API is not covering all the functionalities. Decide how to proceed after talking to Ben.~~ #37

## Dissemination
1. ~~Add links to repos that use the wrappers maybe as a section in the README like "##Used by"~~ #38
1. ~~Find out who can benefit from this work~~ #39
1. ~~Think about events that this work can be advertised~~  #40

**Comment by jspaaks** [comment]
About 

![image](https://user-images.githubusercontent.com/4558105/155970345-463b2a53-95ce-4e0f-b4e2-0c7fc6f895a7.png)
![image](https://user-images.githubusercontent.com/4558105/155970429-83bb786e-a9aa-487b-a1b2-2e0e9f0f5516.png)


Should we spawn separate issues for these and close the current issue?
