### ISSUE TITLE
Overview of refactoring plan

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/cudawrappers#56]
To make the library easy for others to include in their own work, we propose to make a few changes.

We'd like to make the file tree structure more or less as follows:

```plain
.
├── cudawrappers
│   ├── CMakeLists.txt
│   ├── cudawrappers-config.cmake
│   ├── include
│   │   └── cudawrappers.hpp
│   ├── README.md
│   ├── src
│   │   └── cudawrappers.cpp
│   └── tests
│       ├── CMakeLists.txt
│       ├── convolution
│       │   ├── convolution.cpp
│       │   └── README.md
│       ├── README.md
│       └── vector_add
│           ├── README.md
│           ├── vector_add.cpp
│           └── vector_add.cu
└── usage-examples
    ├── cmake-pull
    │   ├── CMakeLists.txt
    │   └── helloworld.cpp
    ├── git-submodule
    │   ├── cudawrappers@0.1.0
    │   └── helloworld.cpp
    ├── locally-installed
    │   ├── CMakeLists.txt
    │   └── helloworld.cpp
    ├── plain-copy
    │   ├── CMakeLists.txt
    │   ├── cudawrappers
    │   └── helloworld.cpp
    └── README.md
```

1. We propose to name the library `cudawrappers`, this will be more consistent across various contexts in which the name will be used
1. `cudawrappers/`:
    1.  contains the library files, with an `include/`, `src/` and `tests/` directory. `src/` should contain the definitions part of what used to be in files `cu/cu.cc`, `cu/cu.h`, `cu/nvrtc.c` and `cu/nvrth.h` in release 0.1.0; `include/` contains the corresponding header files with all declarations. Any definition code that's currrently in `cu/cu.h` or `cu/nvrth.h` should be moved to somewhere under `src/`.
    1. We propose to use filename extensions `.cpp` for implementations and `.hpp` for header files.
    1. `tests/` will contain a few tests, I've put some placeholder directories (`convolution/` and `vector_add/`) there to illustrate the general idea.
1. `usage-examples/` contains some typical ways of how users of the library would access the functionality offered by the cudawrappers library, such as
    1. by including a plain copy of the library source code in their own source tree and building the complete project with CMake (`plain-copy/`);
    1. by including a git submodules copy of the library source code in their own source tree and building the complete project with CMake (`git-submodule/`);
    1. by locally installing the library to an arbitrary place on their system and building their project with CMake (`locally-installed/`);
    1. by having CMake pull in a copy of the library code from GitHub (`cmake-pull/`)

**Comment by jspaaks** [comment]
ping @bouweandela

**Comment by fdiblen** [comment]
ping @csbnw

**Comment by csbnw** [comment]
For the `git-submodule` use-case, one would typically have an `external/cudawrappers` directory in their repository. Therefore, having the `cudawrappers` directory again seems redundant.

**Comment by jspaaks** [comment]
Thanks for the suggestion Bram. We could update the git submodules example by 

```shell
git mv usage-examples/git-submodule/cudawrappers/ usage-examples/git-submodule/external/cudawrappers/ 
```

Would that better represent how consumers would use the library in your opinion?

Regardless, the `plain-copy/` case and the `git-submodules/` case only differ in how consumers get their copy of the dependency, right? Maybe we should consider merging those.

**Comment by jspaaks** [comment]
After rereading https://github.com/nlesc-recruit/CUDA-wrappers/issues/56#issuecomment-1049727626, perhaps this

> Therefore, having the `cudawrappers` directory again seems redundant.

refers to having `cudawrappers/` as well as `git-submodules/cudawrappers/` and `plain-copy/cudawrappers/`, all of which are copies. If that's what you meant: what about making each example its own repository and linking the usage example repos from `cudawrappers/` in its main README.md? The repo names could be:

1. usage-example-plain-copy
2. usage-example-git-submodules
3. usage-example-locallyt-installed
4. usage-example-cmake-pull

**Comment by svlugt** [comment]
In response to: https://github.com/nlesc-recruit/CUDA-wrappers/issues/56#issuecomment-1054121153
Having several example repositories would make sense to me as this is closest to how the library will actually be used.

**Comment by svlugt** [comment]
On second thought, after discussion with @csbnw having separate repositories for the examples seems a worse idea than having recursion in an examples directory. Therefore we favor `usage-examples/git-submodule/external/cudawrappers/ `.
It would be good to include git hooks with _git-submodule update_ to keep the examples in sync.

**Comment by svlugt** [comment]
For now the proposed structure seems fine. When implementing the usage examples we will have to see if the structure supports the different types of usage or if changes are required.
