### ISSUE TITLE
Update ORCID of contributors

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#65]
Make sure in CITATION.cff has correct name, ORCID etc of all the contributors.

**Comment by svlugt** [comment]
@fdiblen 
My email: vlugt@astron.nl
My orcid: https://orcid.org/0000-0001-6834-4860

**Comment by abelsiqueira** [comment]
@john-romein and @csbnw, do you have ORCIDs? If so, can you share the link?
Also, can you confirm the information in https://github.com/nlesc-recruit/cudawrappers/blob/main/CITATION.cff?

**Comment by abelsiqueira** [comment]
@svlugt's information was updated by #128.

**Comment by csbnw** [comment]
My details are as follows:
```
    email: veenboer@astron.nl
    orcid: 'https://orcid.org/0000-0001-9607-1142'
```

**Comment by fdiblen** [comment]
done in #132 and #128
