### ISSUE TITLE
Decide on release policy for version numbering

### ISSUE THREAD

**Issue by svlugt** [nlesc-recruit/cudawrappers#82]
Decide on release policy for version numbering and add this to ["how to release"](https://github.com/nlesc-recruit/CUDA-wrappers/blob/main/README.dev.md#making-a-release).

Suggestion:

- Update major version number for breaking changes, e.g. dropping support for a CUDA version on GPU architecture, changes to the API 
- Update minor version number for small changes that do not directly impact the users
- What to do when we **add** functionality?

**Comment by jspaaks** [comment]
I find semantic versioning a useful paradigm, in particular this part:

![image](https://user-images.githubusercontent.com/4558105/156182961-0b50b0cf-497b-43ea-9a0a-c61edb483517.png)

Many more details on https://semver.org/ :)

**Comment by svlugt** [comment]
Agreed!

**Comment by fdiblen** [comment]
@svlugt We will add this to developer documentation. Can this issue be closed?

**Comment by svlugt** [comment]
Yes
