### ISSUE TITLE
Support interoperability between plain CUDA code and code with cudawrappers

### ISSUE THREAD

**Issue by svlugt** [nlesc-recruit/cudawrappers#85]
The cudawrappers should support mixing plain CUDA code with the cudawrappers. For example when we develop a library that uses the cudawrappers and the library is used in another application that uses plain CUDA code. This means that the cudawrappers should support forwarding of a CUDA context, device pointers, etc (to be investigated).

**Comment by csbnw** [comment]
This issue is too generic and/or does no longer seem relevant. You can update the description and open the issue if needed.
