### ISSUE TITLE
Selective build support for development or deployment

### ISSUE THREAD

**Issue by svlugt** [nlesc-recruit/cudawrappers#86]
A build of the repository will give a different result when build as stand-alone (for development and testing) or when included as sub-module. A stand-alone build should build the included examples, where a build of the cudawrappers when included as a sub-module in another project should only build the wrapper library.

**Comment by fdiblen** [comment]
We should have a CMake variable to build the examples.

If you build by running:
```
cmake -DBUILD_EXAMPLES=on -S . -B build
```
It will compile the examples otherwise, the examples will not be compiled. This variable should be off by deafult.

**Comment by svlugt** [comment]
Yes, something like that.
I would prefer `option(BUILD_TESTING "Build tests" OFF)` as done here: https://git.astron.nl/RD/schaapcommon/-/blob/master/CMakeLists.txt#L14

**Comment by csbnw** [comment]
This issue doesn't seem relevant anymore.
