### ISSUE TITLE
Update LICENSE for files copied from ASTRON repositories

### ISSUE THREAD

**Issue by csbnw** [nlesc-recruit/cudawrappers#94]
This repository uses several files that are copied from ASTRON repositories:
- https://github.com/nlesc-recruit/cudawrappers/blob/main/.clang-format
- https://github.com/nlesc-recruit/cudawrappers/blob/main/.clang-tidy
- https://github.com/nlesc-recruit/cudawrappers/blob/main/.cmake-format.py

This code is licensed under GPL, while cudawrappers use Apache. After an internal discussion, we came up with a solution:
Add something along those license to the LICENSE file:
> This package, except for files in the directory ..., is distributed under the Apache 2 license. Files in the directory ... are released under the GPL license, and obtained from [...].

The files are now located in the root of the repository, putting them in a subdirectory (e.g. `external`, or `formatting`, or `linting`) may make the license text a bit more concise.

**Comment by abelsiqueira** [comment]
@csbnw, the files you mentioned were not copied from ASTRON repositories. They were generated with default values (see the first lines in each of them for details).
That being said, if you want to have the same configuration, the question on how to do it legally still applies.

As for the usage that you mentioned, I am not sure how that works from a legal point of view. Maybe @jspaaks does.

Also, related to #70.

**Comment by csbnw** [comment]
I misunderstood that the files were generated. To be honest, I did not even check the file contents.

Still, the question of how to deal with LICENSES indeed still applies, as we would like to use a common set of style-related set of configurations file for all the software used within ASTRON.

**Comment by fdiblen** [comment]
@csbnw We intentionally did not copy the configuration files from ASTRON as there would be licensing issues.
If you create a pull request to update these configuration files, we will not have any licensing issues. :)
