### ISSUE TITLE
Generate separate objects for each wrapper

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#95]
There should be separate shared objects for the individual wrappers, to avoid that all CUDA libraries (libcuda.so, libcufft.so, libnvrtc.so etc.) need to be linked in as well, even if, for example, the user does not even use cufft).

_Originally posted by @john-romein in https://github.com/nlesc-recruit/cudawrappers/issues/8#issuecomment-1055467037_

**Comment by abelsiqueira** [comment]
Does it make sense to return `cublas.cpp` and `cufft.cpp` to the repo with this change?

**Comment by jspaaks** [comment]
> Does it make sense to return cublas.cpp and cufft.cpp to the repo with this change?

Eventually, yes, but I'd first focus on making the one or two components that we currently have usable with something like:

```cmake
find_package(cudawrappers REQUIRED COMPONENTS nvrtc)
```
