### ISSUE TITLE
Make each component loadable with find_package

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/cudawrappers#96]
Load objects in cmake with `find_package`: e.g. use `find_package(cudawrappers REQUIRED COMPONENTS nvrtc)`

_Originally posted by @svlugt in https://github.com/nlesc-recruit/cudawrappers/issues/8#issuecomment-1055473865_

**Comment by jspaaks** [comment]
What is the list of component names?

**Comment by svlugt** [comment]
- nvrtc
- cuFFT
- "driver API" (the minimum functionality, how to call this?)
- @csbnw @john-romein can you add?

**Comment by csbnw** [comment]
A few that come to mind:
- nvtx
- runtime
- cublas
- cusparse
- cusolver

A complete list with all the libraries can be found [here](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html).

How about we set up a poll to prioritize these?

**Comment by john-romein** [comment]
cuBLASLt, maybe cuBLASXt

**Comment by bouweandela** [comment]
List of associated CMake targets: https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html#imported-targets

**Comment by csbnw** [comment]
How about some bindings for the recent [Python interface](https://nvidia.github.io/cuda-python/overview.html)?

**Comment by bouweandela** [comment]
@csbnw Could you explain a bit more what you would expect of Python bindings?
